### ISSUE TITLE
tune zerolatency on x264enc

### ISSUE THREAD

**Issue by patricksebastien** [umlaeute/pdgst#2]
when using the element x264enc and sending a message:
[tune zerolatency<
|
[x264enc]
i get:
pdgst atom converter failed
cannot convert to 'GstX264EncTune': zerolatency
hmm, couldn't create GValue from atom

gst-inspect-0.10 x264enc:
 tune                : Preset name for non-psychovisual tuning options
                        flags: readable, writable
                        Flags "GstX264EncTune" Default: 0x00000000, "(none)"
                           (0x00000001): stillimage       - Still image
                           (0x00000002): fastdecode       - Fast decode
                           (0x00000004): zerolatency      - Zero latency (requires constant framerate)

**Comment by umlaeute** [comment]
the main problem is, that GStreamer allows to pass arbitrary types (structs, classes,...) as properties, it's obviously not easy to map Pd messages to those arbitrary types in a consisten way. (hence there is currently no support for that).

otoh, if gst-launch can deal with the given property, it should be possible to implement something similar. (in this case this is mainly implementing the "Flags" type.

**Comment by patricksebastien** [comment]
would that be helpful:
http://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer/html/gstreamer-GstUtils.html#gst-util-set-object-arg

__tim on #gstreamer
"...but of course that doesn't work so well for passing actual pointers to actual objects"

**Comment by umlaeute** [comment]
commit 2887149 implements a fallback using gst_util_set_object(), which allows to use e.g. `[tune zerolatency(` or `[tune 0x00000004(`

you still get an error about "atomconverter failed" though (hopefully to be fixed LATER)
